{"name": "test7", "status": "passed", "description": "\n        Common error of calling `dassert()` instead of `dassert_eq()`.\n\n        According to the user's intention the assertion should trigger,\n        but, because of using `dassert()` instead of `dassert_eq()`, the\n        assertion will not trigger. We notice that the user passed a\n        list instead of a string as `msg` and raise.\n        ", "attachments": [{"name": "log", "source": "366c7ed0-4cc0-4e7c-a0a6-c84fe6578ec2-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "94aff9af-1f16-4d05-a678-458557f4c17a-attachment.txt", "type": "text/plain"}], "start": 1656452645230, "stop": 1656452645232, "uuid": "ff4d9318-7a5c-4711-a4a8-c4218a1c23ad", "historyId": "6be930216e1012e5847559ba1f1c17ee", "testCaseId": "b35d7854554391ebac3aa8825adb8be2", "fullName": "helpers.test.test_dbg.Test_dassert1#test7", "labels": [{"name": "parentSuite", "value": "helpers.test"}, {"name": "suite", "value": "test_dbg"}, {"name": "subSuite", "value": "Test_dassert1"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "helpers.test.test_dbg"}]}