17:44:12 @ 2022-06-28 01:44:12 - [36mINFO [0m hunit_test.py setUp:912          
################################################################################
Test_system1.test7
################################################################################
17:44:12 @ 2022-06-28 01:44:12 - [31mERROR[0m hsystem.py _system:274           
################################################################################
cmd='(ls this_file_doesnt_exist) 2>&1' failed with rc='2'
################################################################################
Output of the failing command is:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ls: cannot access 'this_file_doesnt_exist': No such file or directory

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
