{"name": "test_fit_dag1", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 13] Permission denied: '/home/.mxnet'", "trace": "Traceback (most recent call last):\n  File \"/usr/lib/python3.8/pathlib.py\", line 1288, in mkdir\n    self._accessor.mkdir(self, mode)\nFileNotFoundError: [Errno 2] No such file or directory: '/home/.mxnet/gluon-ts/datasets'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.8/pathlib.py\", line 1288, in mkdir\n    self._accessor.mkdir(self, mode)\nFileNotFoundError: [Errno 2] No such file or directory: '/home/.mxnet/gluon-ts'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/dataflow/core/nodes/test/test_gluonts_models.py\", line 35, in test_fit_dag1\n    dag = self._get_dag()\n  File \"/app/dataflow/core/nodes/test/test_gluonts_models.py\", line 52, in _get_dag\n    data, _ = carsigen.get_gluon_dataset(\n  File \"/app/core/artificial_signal_generators.py\", line 56, in get_gluon_dataset\n    dataset = gluonts.dataset.repository.datasets.get_dataset(\n  File \"/venv/lib/python3.8/site-packages/gluonts/dataset/repository/datasets.py\", line 186, in get_dataset\n    dataset_path = materialize_dataset(dataset_name, path, regenerate)\n  File \"/venv/lib/python3.8/site-packages/gluonts/dataset/repository/datasets.py\", line 144, in materialize_dataset\n    path.mkdir(parents=True, exist_ok=True)\n  File \"/usr/lib/python3.8/pathlib.py\", line 1292, in mkdir\n    self.parent.mkdir(parents=True, exist_ok=True)\n  File \"/usr/lib/python3.8/pathlib.py\", line 1292, in mkdir\n    self.parent.mkdir(parents=True, exist_ok=True)\n  File \"/usr/lib/python3.8/pathlib.py\", line 1288, in mkdir\n    self._accessor.mkdir(self, mode)\nPermissionError: [Errno 13] Permission denied: '/home/.mxnet'"}, "attachments": [{"name": "log", "source": "d92ab3aa-1c1f-45be-8207-96458f462ca3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "8d8e5704-a867-493b-bf33-7750e625c4c1-attachment.txt", "type": "text/plain"}], "start": 1656452843089, "stop": 1656452843092, "uuid": "a8957d96-1c7e-4557-937a-e1951e80c40c", "historyId": "0aefd6def3334d8099893502653e5a21", "testCaseId": "e2028a67eff4419772c9f3b5b3caad62", "fullName": "dataflow.core.nodes.test.test_gluonts_models.TestContinuousDeepArModel#test_fit_dag1", "labels": [{"name": "tag", "value": "slow"}, {"name": "parentSuite", "value": "dataflow.core.nodes.test"}, {"name": "suite", "value": "test_gluonts_models"}, {"name": "subSuite", "value": "TestContinuousDeepArModel"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "dataflow.core.nodes.test.test_gluonts_models"}]}