{"name": "test_is_datetime_fail1", "status": "passed", "description": "\n        Test invalid datetime objects.\n        ", "attachments": [{"name": "log", "source": "73aab00c-eb39-4887-8a18-9b5c79a09203-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ffab4d8b-935e-4b49-a85f-3370678b33f3-attachment.txt", "type": "text/plain"}], "start": 1656452653430, "stop": 1656452653431, "uuid": "5d20c53b-e841-4a79-ab11-84d0cc9f38ce", "historyId": "0073d85f5d1375d023cee56fbfde7919", "testCaseId": "89a90c28dfc88065d845662c49b098f8", "fullName": "helpers.test.test_datetime_.Test_dassert_is_datetime1#test_is_datetime_fail1", "labels": [{"name": "parentSuite", "value": "helpers.test"}, {"name": "suite", "value": "test_datetime_"}, {"name": "subSuite", "value": "Test_dassert_is_datetime1"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "helpers.test.test_datetime_"}]}