{"name": "test_predict_dag1", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 13] Permission denied: '/home/.mxnet'", "trace": "Traceback (most recent call last):\n  File \"/usr/lib/python3.8/pathlib.py\", line 1288, in mkdir\n    self._accessor.mkdir(self, mode)\nFileNotFoundError: [Errno 2] No such file or directory: '/home/.mxnet/gluon-ts/datasets'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.8/pathlib.py\", line 1288, in mkdir\n    self._accessor.mkdir(self, mode)\nFileNotFoundError: [Errno 2] No such file or directory: '/home/.mxnet/gluon-ts'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/dataflow/core/nodes/test/test_gluonts_models.py\", line 43, in test_predict_dag1\n    dag = self._get_dag()\n  File \"/app/dataflow/core/nodes/test/test_gluonts_models.py\", line 52, in _get_dag\n    data, _ = carsigen.get_gluon_dataset(\n  File \"/app/core/artificial_signal_generators.py\", line 56, in get_gluon_dataset\n    dataset = gluonts.dataset.repository.datasets.get_dataset(\n  File \"/venv/lib/python3.8/site-packages/gluonts/dataset/repository/datasets.py\", line 186, in get_dataset\n    dataset_path = materialize_dataset(dataset_name, path, regenerate)\n  File \"/venv/lib/python3.8/site-packages/gluonts/dataset/repository/datasets.py\", line 144, in materialize_dataset\n    path.mkdir(parents=True, exist_ok=True)\n  File \"/usr/lib/python3.8/pathlib.py\", line 1292, in mkdir\n    self.parent.mkdir(parents=True, exist_ok=True)\n  File \"/usr/lib/python3.8/pathlib.py\", line 1292, in mkdir\n    self.parent.mkdir(parents=True, exist_ok=True)\n  File \"/usr/lib/python3.8/pathlib.py\", line 1288, in mkdir\n    self._accessor.mkdir(self, mode)\nPermissionError: [Errno 13] Permission denied: '/home/.mxnet'"}, "attachments": [{"name": "log", "source": "0aeec7f7-455e-49c0-8159-b1a0df0b0ac6-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "3b8e5c85-8f5a-4f8a-b2d7-408dbff6da12-attachment.txt", "type": "text/plain"}], "start": 1656452843098, "stop": 1656452843102, "uuid": "5251964a-0778-4b9a-a40d-01e1ed0037f5", "historyId": "a266c20248663f9880a9ef9a537e46eb", "testCaseId": "f3167efb9fe1ac802f3a661528b50481", "fullName": "dataflow.core.nodes.test.test_gluonts_models.TestContinuousDeepArModel#test_predict_dag1", "labels": [{"name": "tag", "value": "slow('~10 seconds.')"}, {"name": "parentSuite", "value": "dataflow.core.nodes.test"}, {"name": "suite", "value": "test_gluonts_models"}, {"name": "subSuite", "value": "TestContinuousDeepArModel"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "dataflow.core.nodes.test.test_gluonts_models"}]}