{"name": "test_is_strict_datetime_fail1", "status": "passed", "description": "\n        Test invalid datetime objects.\n        ", "attachments": [{"name": "log", "source": "af0798cb-f96c-4c40-9b19-03f1d920132d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "6c93b051-c371-48d3-8e26-c72d14a1c121-attachment.txt", "type": "text/plain"}], "start": 1656452653440, "stop": 1656452653442, "uuid": "49b2a667-f2f8-498f-836d-6c97d3bed622", "historyId": "f9dab980e6d8f9bff94628175a6a0cfb", "testCaseId": "a118a4a43355110508d6b4efdfe6b9dc", "fullName": "helpers.test.test_datetime_.Test_dassert_is_datetime1#test_is_strict_datetime_fail1", "labels": [{"name": "parentSuite", "value": "helpers.test"}, {"name": "suite", "value": "test_datetime_"}, {"name": "subSuite", "value": "Test_dassert_is_datetime1"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "helpers.test.test_datetime_"}]}