{"name": "test_dassert_compatible_timestamp_assert1", "status": "passed", "description": "\n        Test a single not compatible pair of datetimes and check the raised\n        exception.\n        ", "attachments": [{"name": "log", "source": "1b1919ab-dc3a-4d96-8ac7-ef971da5709f-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "213428bd-1ad2-432c-876d-949cee92fd1d-attachment.txt", "type": "text/plain"}], "start": 1656452653488, "stop": 1656452653491, "uuid": "decd48ed-137e-49c9-a036-0f94e0852b6b", "historyId": "43f318499d970ca70150494b70b98f78", "testCaseId": "99bb104c07cec27736ce292550e4deb0", "fullName": "helpers.test.test_datetime_.Test_dassert_tz_compatible1#test_dassert_compatible_timestamp_assert1", "labels": [{"name": "parentSuite", "value": "helpers.test"}, {"name": "suite", "value": "test_datetime_"}, {"name": "subSuite", "value": "Test_dassert_tz_compatible1"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "helpers.test.test_datetime_"}]}